config/routes.rb
Rails.application.routes.draw do
  get 'static/home'
  get 'static/biz'
  get 'static/bizpricing'
  get 'static/perpricing'
  resources :subscribers

  
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :only => [:show]

  root 'static#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :lines, :numericality => { :greater_than => 0, :less_than_or_equal_to => 100, :message => 
                                          "Number of users must be grater than 0 and less than 100" }
  validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/subscribers/new'
  end
  
  private

  def sign_up_params
    params.require(:user).permit(:whichmodel, :email,:name, :phone, :lines, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:whichmodel, :email, :name, :phone, :lines, :password, :password_confirmation, :current_password)
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  
  def home
  end
  
  def biz
  end
  
  def bizpricing
  end
  
  def perpricing
  end
  
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
    before_filter :authenticate_user!
    
    def new
        if current_user.whichmodel == "Business"
            if current_user.lines < 11
                planes = 101
            else
                planes = 102
            end
        else
            planes = 103
        end
    end
    
    def create
        if current_user.whichmodel == "Business"
            if current_user.lines < 11
                planes = 101
            else
                planes = 102
            end
        else
            planes = 103
        end
        
        @code = params[:couponCode]
        
        #gets the credit card details submitted in the form
        token = params[:stripeToken]
        
        if params[:couponCode] == ""
            customer = Stripe::Customer.create(
              card: token,
              quantity: current_user.lines,
              plan: planes,
              email: current_user.email
            )
        else
            #create a customer
            customer = Stripe::Customer.create(
              card: token,
              quantity: current_user.lines,
              plan: planes,
              coupon: @code,
              email: current_user.email
            )
        end
        
        current_user.subscribed = true
        current_user.stripeid = customer.id
        current_user.save
    
    
        redirect_to static_home_path, notice: "Your subscription was set up successfully!"
        
    end
    
    
    def index
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer" class="bg-dark section-p-sm text-white">
    <div class="container">
      <div class="row">

        <!-- Company Details -->
        <div class="col-md-6 wrapper-v-sm text-center-md">
          <p class="text-light">
            <a class="link-white" href="#">Terms</a>
            <span class="separator">|</span>
            <a class="link-white" href="#">Imprint</a>
            <span class="separator">|</span>
            <a class="link-white" href="#">Privacy
              Policy</a><br>
            © 2016 <%= image_tag("logo-white.png", :alt => "", :class => "logo-wrapper", :height => "18") %>.
            All Rights Reserved. Sources: <a class="link-white"
                                             href="" target="_blank"
                                             data-placement="top"
                                             data-toggle="tooltip" title="&copy; name1
  &copy; name2
  &copy; name3
  &copy; name4">dailholic</a>
          </p>
        </div>
        <!-- /End Company Details -->

        <!-- Buttons Social -->
        
        <!-- /End Buttons Social -->

      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<!-- Preloader -->


<!-- Main -->
<div id="page" class="light-version">


  <!-- ============================
       Navigation Header
  ================================= -->

  <header id="nav" class="light-nav">

    <!-- Sticky Navigation -->
    <!-- for static Navbar: remove navbar-fixed-top; add navbar-static-top and navbar-light-->
    <nav class="navbar navbar-static-top">
      <div class="container">
        <div class="navbar-header">

          <!-- Menu Button for Mobile Devices -->
          <button type="button" class="collapse navbar-toggle navbar-icon" data-toggle="collapse"
                  data-target="#navbar-collapse">
            <span></span>
            <span></span>
            <span></span>
          </button>

          <!-- Logo -->
          <a href="/" class="navbar-brand logo-color smooth-scroll"><span></span></a>

        </div>
        <!-- /End Navbar hero -->

        <div class="collapse navbar-collapse-md" id="navbar-collapse">

          <!-- Navigation Links -->
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", root_path %></li>
            <li><a href="#function" class="smooth-scroll">Function</a></li>
            <li><a href="#pricing" class="smooth-scroll">Pricing</a></li>
            <% if params[:action] == 'biz' %>
              <li><a href="/static/home" class="smooth-scroll">Residential</a></li>
            <% else params[:action] == 'home' %>
              <li><a href="/static/biz" class="smooth-scroll">Business</a></li>
            <% end %>
          </ul>

          <!-- Social Links -->
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
          <!-- /End Navigation Links -->

        </div>
        <!-- /End Navbar Collapse -->

      </div>
    </nav>
    <!-- /END Sticky Navigation -->

  </header>
</div>

app/views/layouts/_header1.html.erb
<!-- Preloader -->


<!-- Main -->
<div id="page" class="light-version">


  <!-- ============================
       Navigation Header
  ================================= -->

  <header id="nav" class="light-nav">

    <!-- Sticky Navigation -->
    <!-- for static Navbar: remove navbar-fixed-top; add navbar-static-top and navbar-light-->
    <nav class="navbar navbar-static-top navbar-light">
      <div class="container">
        <div class="navbar-header">

          <!-- Menu Button for Mobile Devices -->
          <button type="button" class="collapse navbar-toggle navbar-icon" data-toggle="collapse"
                  data-target="#navbar-collapse">
            <span></span>
            <span></span>
            <span></span>
          </button>

          <!-- Logo -->
          <a href="#page" class="navbar-brand logo-color smooth-scroll"><span></span></a>

        </div>
        <!-- /End Navbar hero -->

        <div class="collapse navbar-collapse-md" id="navbar-collapse">

          <!-- Navigation Links -->
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", root_path %></li>
            <li><a href="/static/home" class="smooth-scroll">Personal</a></li>
            <li><a href="/static/biz" class="smooth-scroll">Business</a></li>
            <li><a href="" class="smooth-scroll">Features</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Pricing <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="/static/bizpricing" class="smooth-scroll">Business</a></li>
                  <li><a href="/static/perpricing" class="smooth-scroll">Residential</a></li>
                </ul>
              </li>
          </ul>

          <!-- Social Links -->
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
          <!-- /End Navigation Links -->

        </div>
        <!-- /End Navbar Collapse -->

      </div>
    </nav>
    <!-- /END Sticky Navigation -->

  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailHolic – Future of Communication</title>
    <meta name="description"
          content="Best phone service provider"/>
    <meta name="keywords"
          content="Voip, Phone, Phone Provider, Cheap Phone, Cloud Phone, UC"/>
    <meta name="author" content="Egotype">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body>
    <% if content_for?(:navbar) %>
      <%= yield(:navbar) %>
    <% else %>
      <%= render 'layouts/header1' %>
    <% end %>
    
    <%= yield %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= render 'layouts/footer' %>

</body>
</html>

app/views/subscribers/_form.html.erb
<%= form_tag subscribers_path do %>

  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <p>
    <label class="amount">
      <h5>Number of Users: <%= current_user.lines %></h5><br>
      <% if current_user.whichmodel == "Business" %>
            <% if current_user.lines < 11 %>
                <h5>Plan: $0.97</h5><br>
                <h5>Period: 30 days</h5><br><br>
                <h5>Total: $<%= current_user.lines * 0.97 * 30 %></h5><br><br>
            <% else %>
                <h5>Plan: $0.84</h5><br>
                <h5>Period: 30 days</h5><br><br>
                <h5>Total: $<%= current_user.lines * 0.84 * 30 %></h5><br><br>
            <% end %>
        <% else %>
            <h5>Plan: $0.84</h5><br>
            <h5>Period: 30 days</h5><br><br>
            <h5>Total: $<%= current_user.lines * 0.84 * 30 %></h5><br><br>
        <% end %>
      <%=link_to "Change Setting", edit_user_registration_path %>
    </label>
  </p>
  <p>
    <%= label_tag(:couponCode, 'Coupon:') %>
    <%= text_field_tag(:couponCode) %>
  </p>
  
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
          data-description="A month's subscription"
          data-amount=""></script>
<% end %>

app/views/subscribers/index.html.erb
<h2>Thanks, you paid <strong>$29.00</strong>!</h2>

app/views/subscribers/new.html.erb
<div class="body-login">
  <div class="login">
  		<div class="login-screen">
  		    <div class="app-title">
                <h2>Final Step</h2><br>
            </div>
                <p>This is the final step to give you full access</p>  
                <%= render 'form' %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="body-login-v2">
  <div class="login">
  		<div class="login-screen">
  		    <div class="app-title">
                <h2><%= @user.name %></h2><br>
            </div>
            <h4>Email: <%= @user.email %></h4>
            <h4>Number of line: <%= @user.lines %></h4>
            <h4>Subscribtion Plan: <%= @user.whichmodel %></h4>
            <h4>Subscribtion Status: <%= @user.subscribed %></h4><br>
            <%=link_to "Edit Your Profile", edit_user_registration_path %>
        </div>
    </div>
</div>